import type { Time } from '@/msgs/StdMsgs'

/**
 * Severity level constants matching rcl_interfaces/msg/Log.msg.
 * Values follow Python logging levels and rcutils logging implementation.
 */
export const RCL_LOG_LEVEL_DEBUG = 10 as const // Debug information for diagnosing issues.
export const RCL_LOG_LEVEL_INFO = 20 as const // Standard informational level.
export const RCL_LOG_LEVEL_WARN = 30 as const // Potential issues or unexpected behavior.
export const RCL_LOG_LEVEL_ERROR = 40 as const // Errors this node cannot resolve.
export const RCL_LOG_LEVEL_FATAL = 50 as const // Information about an impending node shutdown.

export type RclLogLevel =
  | typeof RCL_LOG_LEVEL_DEBUG
  | typeof RCL_LOG_LEVEL_INFO
  | typeof RCL_LOG_LEVEL_WARN
  | typeof RCL_LOG_LEVEL_ERROR
  | typeof RCL_LOG_LEVEL_FATAL

/**
 * rcl_interfaces/msg/Log message definition.
 */
export type RclLog = {
  stamp: Time // Timestamp when this message was generated by the node.
  level: RclLogLevel // Corresponding log level as defined above.
  name: string // Name representing the logger/node.
  msg: string // Full log message.
  file: string // Source file.
  function: string // Function in the source file.
  line: number // Line number in the source file.
}
