name: Main CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

permissions:
  contents: read

jobs:
  editorconfig-check:
    name: EditorConfig Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # 最近のバージョンのタグがないためコミットIDを指定
      - uses: editorconfig-checker/action-editorconfig-checker@48920075d6a466d902d683b648b6365703e49293

      - name: EditorConfig Check
        run: editorconfig-checker

  quality-check:
    name: Lint, Format, and Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun ci

      - name: Check Format
        run: bun run check:format

      - name: Check Lint
        run: bun run check:lint

      - name: Build
        run: bun run build
